Update screenshots
tenacityteam/assets pull request #6
Opened 2021-08-09 22:08 UTC by vchernin

-Replace previous 3840x2160 ones with actual 3840x2160 ones
-Add 1280x720 screenshots

I couldn't take 1920x1080 screenshots natively without the interface looking way too big or too small. I think it'd be best to scale them down like in https://github.com/tenacityteam/assets/pull/5.

cc @TheEvilSkeleton @SFR-git

2021-08-09 22:14 UTC, TheEvilSkeleton commented
> I couldn't take 1920x1080 screenshots natively without the interface looking way too big or too small. I think it'd be best to scale them down like in #5.

The issue is still open so @SFR-git could adapt it in the MR.

2021-08-09 22:14 UTC, TheEvilSkeleton approved these changes

2021-08-10 05:41 UTC, SFR-git reviewed
I'm going to rebase this in a bit.

2021-08-10 05:41 UTC, SFR-git commented on README.md
> +`screenshots/tenacity-screenshot-light-3840x2160.png`, `screenshots/tenacity-screenshot-dark-3840x2160.png`, `screenshots/tenacity-screenshot-light-1280x720.png` and `screenshots/tenacity-screenshot-
Nitpick: Oxford comma?

2021-08-10 13:10 UTC, SFR-git commented
Do you want to add a downscaled 1080p version as well? Or are we fine with 4K/720p?

2021-08-10 13:11 UTC, TheEvilSkeleton commented
1080p would be nice to be honest.

2021-08-10 13:16 UTC, SFR-git commented
I'm going to scale them down and finalize the commit, then

2021-08-10 14:29 UTC, SFR-git commented
@TheEvilSkeleton: be advised that you will need to update the links in the manifest, as they're linked to a specific commit hash.

2021-08-10 14:36 UTC, TheEvilSkeleton commented
@SFR-git I know.

2021-08-10 14:43 UTC, SFR-git approved these changes

2021-08-10 14:44 UTC, TheEvilSkeleton approved these changes

2021-08-10 14:48 UTC, TheEvilSkeleton requested changes
Actually, I just realized something.

2021-08-10 14:48 UTC, TheEvilSkeleton commented on README.md
> +All images under `screenshots/` are licensed to the Tenacity project under the CC BY 4.0 by Vincent Chernin.
This should be at least inside LICENSE.md. It's fine if it's in the README but I'm pretty sure it's crucial for it to be in the license file. Here's an example from GitLab: https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE#L3-10

2021-08-10 14:51 UTC, SFR-git commented on README.md
> +All images under `screenshots/` are licensed to the Tenacity project under the CC BY 4.0 by Vincent Chernin.
Well, since the entire repository is licensed under CC BY 4.0, that's irrelevant.

2021-08-10 14:52 UTC, TheEvilSkeleton commented on README.md
> +All images under `screenshots/` are licensed to the Tenacity project under the CC BY 4.0 by Vincent Chernin.
Huh, you're right/

2021-08-10 14:53 UTC, TheEvilSkeleton approved these changes

2021-08-10 14:54 UTC, closed without merging

2021-08-10 16:28 UTC, vchernin commented
I just realized `tenacity-screenshot-light-1280x720.png` has a 2 in the top left since my display settings were left open… Whoops that’s definitely my bad.

I’ll fix that in a new PR I guess.